version: '3.1'

services:
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: my-root-password
            MYSQL_USER: my-signing-server-user
            MYSQL_PASSWORD: my-signing-server-password
            MYSQL_DATABASE: signserver
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

    signserver:
        image: linuxianer99/primekey-signing-server-ce:5.2.0
        privileged: true
        cap_add:
            - CAP_SYS_ADMIN
        ports:
            - 8080:8080/tcp
            - 8443:8443/tcp
            - 9990:9990/tcp
        depends_on: 
            - db
        environment:
            SIGNSERVER_MYSQL_USER: my-signing-server-user
            SIGNSERVER_MYSQL_PASSWORD: my-signing-server-password
            SIGNSERVER_MYSQL_HOST: db
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro

# The following php admin interface can be enabled for debugging. 
#    adminer:
#        image: adminer
#        ports:
#            - 8081:8080

